# Generated by Django 4.2.3 on 2023-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type_of_user",
            field=models.CharField(
                choices=[
                    ("super_admin", "SUPER_ADMIN"),
                    ("company_owner", "COMANY_OWNER"),
                ],
                default="super_admin",
                max_length=20,
            ),
        ),
    ]
