# Generated by Django 4.2.3 on 2023-07-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
    ]
