# Generated by Django 4.2.3 on 2023-08-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_customer_event_inventory_skill_quotation_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="skills",
            new_name="skill_id",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="base_price",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="sell_price",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
