# Generated by Django 4.2.3 on 2023-08-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_customer_address_quotation_due_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="nots",
            new_name="notes",
        ),
    ]
