# Generated by Django 4.2.3 on 2023-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_quotation_json_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="converted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
