# Generated by Django 4.2.3 on 2023-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_quotation_event_venue_alter_staff_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
