# Generated by Django 4.2.3 on 2023-08-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_quotation_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="final_amount",
            field=models.IntegerField(default=0),
        ),
    ]
