# Generated by Django 4.2.3 on 2023-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_staff_social_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="social_media",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="couple_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
