# Generated by Django 4.2.3 on 2023-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_staff_studio_name_staff_is_eposure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "PAID"), ("pending", "PENDING")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
