# Generated by Django 4.2.3 on 2023-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_quotation_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="social_media",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="social_media",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="studiodetails",
            name="social_media",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
