# Generated by Django 4.2.3 on 2023-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_customer_social_media_alter_staff_social_media_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "CASH"),
                    ("cheque", "CHEQUE"),
                    ("net_banking", "NET BANKING"),
                    ("upi", "UPI"),
                ],
                default="cash",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "SALE"),
                    ("payment_in", "PAYMENT IN"),
                    ("payment_out", "PAYMENT OUT"),
                    ("expense", "EXPENSE"),
                ],
                default="payment_in",
                max_length=15,
            ),
        ),
    ]
