# Generated by Django 4.2.3 on 2023-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_transaction_payment_type_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("sale", "SALE"),
                    ("service", "SERVICE"),
                    ("purchase", "PURCHASE"),
                ],
                default="services",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "SALE"),
                    ("payment_in", "PAYMENT IN"),
                    ("payment_out", "PAYMENT OUT"),
                    ("expense", "EXPENSE"),
                    ("purchase", "PURCHASE"),
                ],
                default="payment_in",
                max_length=15,
            ),
        ),
    ]
