# Generated by Django 4.2.3 on 2023-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_category_item_transaction_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("sale", "SALE"),
                    ("service", "SERVICE"),
                    ("purchase", "PURCHASE"),
                ],
                default="service",
                max_length=10,
            ),
        ),
    ]
