# Generated by Django 4.2.3 on 2023-08-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_remove_item_category_id"),
        ("app", "0027_remove_item_category_id_delete_category_delete_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="expense_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.expense",
            ),
        ),
    ]
