# Generated by Django 4.2.3 on 2023-08-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_transaction_expense_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="discount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="final_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
