# Generated by Django 4.2.3 on 2023-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_quotation_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Cash", "CASH"),
                    ("Cheque", "CHEQUE"),
                    ("Net_banking", "NET BANKING"),
                    ("Upi", "UPI"),
                ],
                default="Cash",
                max_length=15,
            ),
        ),
    ]
