# Generated by Django 4.2.3 on 2023-08-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_transaction_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_venue", models.CharField(blank=True, null=True)),
                ("evnet_time", models.TimeField(blank=True, null=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.event",
                    ),
                ),
                (
                    "eventday_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.eventday",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="event_id",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="event_venue",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="json_data",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="start_date",
        ),
        migrations.CreateModel(
            name="InventoryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0.0, max_length=10)),
                (
                    "eventday_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.eventday",
                    ),
                ),
                (
                    "inventory_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExposureDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0.0, max_length=10)),
                (
                    "eventdetails_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.eventdetails",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.staff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventdetails",
            name="quotation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.quotation",
            ),
        ),
        migrations.AddField(
            model_name="eventday",
            name="quotation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.quotation",
            ),
        ),
    ]
