# Generated by Django 4.2.3 on 2023-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_eventday_eventdetails_remove_quotation_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventdetails",
            old_name="evnet_time",
            new_name="end_time",
        ),
        migrations.AddField(
            model_name="eventdetails",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorydetails",
            name="profit",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name="inventorydetails",
            name="qty",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
