# Generated by Django 4.2.3 on 2023-08-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_rename_evnet_time_eventdetails_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exposuredetails",
            name="inventorydetails_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.inventorydetails",
            ),
        ),
    ]
