# Generated by Django 4.2.3 on 2023-08-31 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_exposuredetails_inventorydetails_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.customer",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="discount_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_orderConverted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="profit",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recived_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="round_off",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(blank=True, null=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customer",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.staff",
                    ),
                ),
            ],
        ),
    ]
