# Generated by Django 4.2.3 on 2023-09-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_transaction_balance_amount_transaction_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exposuredetails",
            name="eventdetails_id",
        ),
        migrations.AddField(
            model_name="exposuredetails",
            name="eventdetails_id",
            field=models.ManyToManyField(to="app.eventdetails"),
        ),
    ]
