# Generated by Django 4.2.3 on 2023-09-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_remove_exposuredetails_eventdetails_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exposuredetails",
            old_name="eventdetails_id",
            new_name="eventdetails",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="quotation_id",
        ),
        migrations.AddField(
            model_name="quotation",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.transaction",
            ),
        ),
    ]
