# Generated by Django 4.2.3 on 2023-09-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_rename_eventdetails_id_exposuredetails_eventdetails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotation",
            old_name="transaction",
            new_name="transaction_id",
        ),
    ]
