# Generated by Django 4.2.3 on 2023-09-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_rename_is_orderconverted_transaction_is_converted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="staff_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.staff",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "SALE"),
                    ("purchase", "PURCHASE"),
                    ("payment_in", "PAYMENT IN"),
                    ("payment_out", "PAYMENT OUT"),
                    ("sale_order", "SALE ORDER"),
                    ("purchase_order", "PURCHASE ORDER"),
                    ("estimate", "ESTIMATE"),
                    ("expense", "EXPENSE"),
                ],
                default="payment_in",
                max_length=15,
            ),
        ),
    ]
