# Generated by Django 4.2.3 on 2023-09-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_transaction_type_transactiondescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiondescription",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transactiondescription_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.transactiondescription",
            ),
        ),
    ]
