# Generated by Django 4.2.3 on 2023-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_remove_transactiondescription_transaction_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransactionDescription",
            new_name="InventoryDescription",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transactiondescription_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="inventorydescription",
            field=models.ManyToManyField(blank=True, to="app.inventorydescription"),
        ),
    ]
