# Generated by Django 4.2.3 on 2023-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_linktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="used_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
