# Generated by Django 4.2.3 on 2023-09-06 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_transaction_used_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="notes",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
