# Generated by Django 4.2.3 on 2023-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_quotation_user_id_remove_transaction_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="balance_amount",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="recived_amount",
        ),
        migrations.AddField(
            model_name="transaction",
            name="recived_or_paid_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
