# Generated by Django 4.2.3 on 2023-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_rename_balance_amount_transaction_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
