# Generated by Django 4.2.3 on 2023-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_user_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="settled_amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
