# Generated by Django 4.2.3 on 2023-09-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_transaction_settled_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payee_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="payee_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
