# Generated by Django 4.2.3 on 2023-10-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_transaction_advance_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile_no",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="staff",
            name="mobile_no",
            field=models.CharField(max_length=15),
        ),
    ]
