# Generated by Django 4.2.3 on 2023-11-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_customer_mobile_no_alter_staff_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="exposuredetails_ids",
            field=models.ManyToManyField(
                blank=True, related_name="exposuredetails_ids", to="app.exposuredetails"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="parent_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_transactions",
                to="app.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="exposuredetails_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_exposuredetails",
                to="app.exposuredetails",
            ),
        ),
    ]
