# Generated by Django 4.2.3 on 2023-12-13 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_transaction_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorydescription",
            name="quotation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.quotation",
            ),
        ),
        migrations.CreateModel(
            name="EventExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.TextField(blank=True, max_length=2000, null=True)),
                ("price", models.FloatField(default=0.0, max_length=10)),
                (
                    "quotation_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.quotation",
                    ),
                ),
            ],
        ),
    ]
