# Generated by Django 4.2.3 on 2024-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_cashandbank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashandbank",
            name="type",
            field=models.CharField(
                choices=[("cash", "CASH"), ("bank", "BANK")],
                default="cash",
                max_length=15,
            ),
        ),
    ]
