# Generated by Django 4.2.3 on 2023-08-24 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expense", "0002_remove_item_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name="expenseitem",
            name="amount",
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
