# Generated by Django 4.2.3 on 2023-08-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_item_user_id_alter_expense_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseitem",
            name="category_id",
        ),
        migrations.AddField(
            model_name="expense",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.category",
            ),
        ),
    ]
